_: {
  flake.neovimModules.extraPackages = {pkgs, ...}: {
    config.vim.extraPackages = with pkgs; [
      ansible-language-server
      astro-language-server
      autotools-language-server
      bash-language-server
      clang-tools
      clojure-lsp
      cmake-language-server
      curl
      deadnix
      dockerfile-language-server
      elixir-ls
      fish-lsp
      git
      gopls
      glsl_analyzer
      haskell-language-server
      imagemagick
      jdt-language-server
      jinja-lsp
      just-lsp
      kotlin-language-server
      lemminx
      lua-language-server
      nixd
      nodejs
      oxlint
      prettier
      ruby-lsp
      ruff
      rust-analyzer
      shellcheck
      shfmt
      sqls
      statix
      stylua
      svelte-language-server
      taplo
      terraform-ls
      texlab
      tree-sitter
      tinymist
      ty
      typescript-language-server
      vscode-langservers-extracted
      zls
    ];
  };
}
